require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomAttributesController do

  # This should return the minimal set of attributes required to create a valid
  # CustomAttribute. As you add validations to CustomAttribute, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  name: "MyString",
                              value: "value",
                              room_id: 3 } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomAttributesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all custom_attributes as @custom_attributes" do
      custom_attribute = CustomAttribute.create! valid_attributes
      get :index, {}, valid_session
      assigns(:custom_attributes).should eq([custom_attribute])
    end
  end

  describe "GET show" do
    it "assigns the requested custom_attribute as @custom_attribute" do
      custom_attribute = CustomAttribute.create! valid_attributes
      get :show, {:id => custom_attribute.to_param}, valid_session
      assigns(:custom_attribute).should eq(custom_attribute)
    end
  end

  describe "GET new" do
    it "assigns a new custom_attribute as @custom_attribute" do
      get :new, {}, valid_session
      assigns(:custom_attribute).should be_a_new(CustomAttribute)
    end
  end

  describe "GET edit" do
    it "assigns the requested custom_attribute as @custom_attribute" do
      custom_attribute = CustomAttribute.create! valid_attributes
      get :edit, {:id => custom_attribute.to_param}, valid_session
      assigns(:custom_attribute).should eq(custom_attribute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomAttribute" do
        expect {
          post :create, {:custom_attribute => valid_attributes}, valid_session
        }.to change(CustomAttribute, :count).by(1)
      end

      it "assigns a newly created custom_attribute as @custom_attribute" do
        post :create, {:custom_attribute => valid_attributes}, valid_session
        assigns(:custom_attribute).should be_a(CustomAttribute)
        assigns(:custom_attribute).should be_persisted
      end

      it "redirects to the created custom_attribute" do
        post :create, {:custom_attribute => valid_attributes}, valid_session
        response.should redirect_to(CustomAttribute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved custom_attribute as @custom_attribute" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:custom_attribute => { "name" => "invalid value" }}, valid_session
        assigns(:custom_attribute).should be_a_new(CustomAttribute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:custom_attribute => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested custom_attribute" do
        custom_attribute = CustomAttribute.create! valid_attributes
        # Assuming there are no other custom_attributes in the database, this
        # specifies that the CustomAttribute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomAttribute.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => custom_attribute.to_param, :custom_attribute => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested custom_attribute as @custom_attribute" do
        custom_attribute = CustomAttribute.create! valid_attributes
        put :update, {:id => custom_attribute.to_param, :custom_attribute => valid_attributes}, valid_session
        assigns(:custom_attribute).should eq(custom_attribute)
      end

      it "redirects to the custom_attribute" do
        custom_attribute = CustomAttribute.create! valid_attributes
        put :update, {:id => custom_attribute.to_param, :custom_attribute => valid_attributes}, valid_session
        response.should redirect_to(custom_attribute)
      end
    end

    describe "with invalid params" do
      it "assigns the custom_attribute as @custom_attribute" do
        custom_attribute = CustomAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom_attribute.to_param, :custom_attribute => { "name" => "invalid value" }}, valid_session
        assigns(:custom_attribute).should eq(custom_attribute)
      end

      it "re-renders the 'edit' template" do
        custom_attribute = CustomAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom_attribute.to_param, :custom_attribute => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested custom_attribute" do
      custom_attribute = CustomAttribute.create! valid_attributes
      expect {
        delete :destroy, {:id => custom_attribute.to_param}, valid_session
      }.to change(CustomAttribute, :count).by(-1)
    end

    it "redirects to the custom_attributes list" do
      custom_attribute = CustomAttribute.create! valid_attributes
      delete :destroy, {:id => custom_attribute.to_param}, valid_session
      response.should redirect_to(custom_attributes_url)
    end
  end

end
