require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoomsController do

  let(:organization) { FactoryGirl.create(:organization)}
  let(:location) { FactoryGirl.create(:location)}

  # This should return the minimal set of attributes required to create a valid
  # Room. As you add validations to Room, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  name: "MyString",
                              price_per_hour: 9.99,
                              location_id: location.id,
                              organization_id: organization.id,
                              people_capacity: 12 } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RoomsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  context "user NOT logged in" do

    describe "GET index" do
      it "redirects to the home page" do
        get :index, {}, valid_session
        response.should redirect_to(new_user_session_path)
      end
    end

    describe "GET show" do
      it "redirects to the home page" do
        room = Room.create! valid_attributes
        get :show, {:id => room.to_param}, valid_session
        response.should redirect_to(new_user_session_path)
      end
    end

    describe "GET new" do
      it "redirects to the home page" do
        get :new, {}, valid_session
        response.should redirect_to(new_user_session_path)
      end
    end

    describe "GET edit" do
      it "redirects to the home page" do
        room = Room.create! valid_attributes
        get :edit, {:id => room.to_param}, valid_session
        response.should redirect_to(new_user_session_path)
      end
    end

    describe "POST create" do
      it "does NOT create" do
        expect {
            post :create, {:room => valid_attributes}, valid_session
          }.to_not change(Room, :count).by(1)
      end

      it "redirects to the home page" do
        post :create, {:room => valid_attributes}, valid_session
        response.should redirect_to(new_user_session_path)
      end
    end

    describe "PUT update" do
      it "does NOT update" do
        room = Room.create! valid_attributes
        put :update, {:id => room.to_param, :room => valid_attributes}, valid_session
        Room.any_instance.should_not_receive(:update).with(valid_attributes)
      end

      it "redirects to the home page" do
        room = Room.create! valid_attributes
        put :update, {:id => room.to_param, :room => valid_attributes}, valid_session
        response.should redirect_to(new_user_session_path)
      end
    end

    describe "DELETE destroy" do
      it "does NOT delete" do
        room = Room.create! valid_attributes
        delete :destroy, {:id => room.to_param}, valid_session
        expect(Room.count).to eq 1
      end

      it "redirects to the home page" do
        room = Room.create! valid_attributes
        delete :destroy, {:id => room.to_param}, valid_session
        response.should redirect_to(new_user_session_path)
      end
    end
  end


  context "user logged in" do

    before :each do
      @request.env["devise.mapping"]= Devise.mappings[:user]
      @user = FactoryGirl.create(:user)
      sign_in @user
    end

    describe "GET index" do
      it "assigns all rooms as @rooms" do
        room = Room.create! valid_attributes
        get :index, {}, valid_session
        assigns(:rooms).should eq([room])
      end
    end

    describe "GET show" do
      it "assigns the requested room as @room" do
        room = Room.create! valid_attributes
        get :show, {:id => room.to_param}, valid_session
        assigns(:room).should eq(room)
      end
    end

    describe "GET new" do
      it "assigns a new room as @room" do
        organization = FactoryGirl.create(:organization)
        get :new, {:organization_id => organization.id}, valid_session
        assigns(:room).should be_a_new(Room)
      end
    end

    describe "GET edit" do
      it "assigns the requested room as @room" do
        room = Room.create! valid_attributes
        get :edit, {:id => room.to_param}, valid_session
        assigns(:room).should eq(room)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Room" do
          expect {
            post :create, {:room => valid_attributes}, valid_session
          }.to change(Room, :count).by(1)
        end

        it "assigns a newly created room as @room" do
          post :create, {:room => valid_attributes}, valid_session
          assigns(:room).should be_a(Room)
          assigns(:room).should be_persisted
        end

        it "redirects to the Organization show page" do
          post :create, {:room => valid_attributes}, valid_session
          response.should redirect_to(organization_path(valid_attributes[:organization_id]))
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved room as @room" do
          # Trigger the behavior that occurs when invalid params are submitted
          Room.any_instance.stub(:save).and_return(false)
          post :create, {:room => { "name" => "invalid value" }}, valid_session
          assigns(:room).should be_a_new(Room)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          Room.any_instance.stub(:save).and_return(false)
          post :create, {:room => { "name" => "invalid value" }}, valid_session
          response.should render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        it "updates the requested room" do
          room = Room.create! valid_attributes
          # Assuming there are no other rooms in the database, this
          # specifies that the Room created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          Room.any_instance.should_receive(:update).with({ "name" => "MyString" })
          put :update, {:id => room.to_param, :room => { "name" => "MyString" }}, valid_session
        end

        it "assigns the requested room as @room" do
          room = Room.create! valid_attributes
          put :update, {:id => room.to_param, :room => valid_attributes}, valid_session
          assigns(:room).should eq(room)
        end

        it "redirects to the room" do
          room = Room.create! valid_attributes
          put :update, {:id => room.to_param, :room => valid_attributes}, valid_session
          response.should redirect_to(room.organization)
        end
      end

      describe "with invalid params" do
        it "assigns the room as @room" do
          room = Room.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          Room.any_instance.stub(:save).and_return(false)
          put :update, {:id => room.to_param, :room => { "name" => "invalid value" }}, valid_session
          assigns(:room).should eq(room)
        end

        it "re-renders the 'edit' template" do
          room = Room.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          Room.any_instance.stub(:save).and_return(false)
          put :update, {:id => room.to_param, :room => { "name" => "invalid value" }}, valid_session
          response.should render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested room" do
        room = Room.create! valid_attributes
        expect {
          delete :destroy, {:id => room.to_param}, valid_session
        }.to change(Room, :count).by(-1)
      end

      it "redirects to the ORganization show page" do
        room = Room.create! valid_attributes
        delete :destroy, {:id => room.to_param}, valid_session
        response.should redirect_to(organization_path(room.organization))
      end
    end

  end

end
